services:
  web:
    build: .
    container_name: remap_web
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --threads 2 config.wsgi:application
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8001:8000"
    restart: always

volumes:
  static_volume: